### ISSUE TITLE
Unfortunately, the widget does not work again

### ISSUE THREAD

**Issue by michel0271** [thejosejorge/futcal-for-scriptable#28]
Hi, probably another change in their api?

greetings 
michel

**Comment by michel0271** [comment]
Is there no way to get the widget to work anymore?

**Comment by michel0271** [comment]
I unfortunately Futcal.js updated without success. Error is still there.
![IMG_0366](https://user-images.githubusercontent.com/39130531/125485545-4f4137db-f06e-45a7-b4fa-51f28eb6406e.jpeg)

**Comment by lcshmn** [comment]
Have you updated your script [with the code](https://github.com/thejosejorge/futcal-for-scriptable/blob/6e91197d41abcc8f29ffc497d9920b4e22069699/Futcal.js) from my pull request?
Because right now my pull request hasn't been reviewed and @thejosejorge still has to decide if he will merge it or rewrite/optimize it on his own.

**Comment by michel0271** [comment]
> Have you updated your script [with the code](https://github.com/thejosejorge/futcal-for-scriptable/blob/6e91197d41abcc8f29ffc497d9920b4e22069699/Futcal.js) from my pull request?
> Because right now my pull request hasn't been reviewed and @thejosejorge still has to decide if he will merge it or rewrite/optimize it on his own.

Sorry my mistake. It works again with your code! Many Thanks!!!

**Comment by thejosejorge** [comment]
Hi @michel0271, @lcshmn,

This was indeed another API change!
Apologies, I had the fix ready and I was already using it. I thought I published it but apparently I didn't, thank you for the reminder. The change was similar to the one provided by @lcshmn, I tried to simplify the code a bit since some things are no longer required.

Thanks,
Jose
