### ISSUE TITLE
Add option for live playing time

### ISSUE THREAD

**Issue by monza258** [thejosejorge/futcal-for-scriptable#3]
Hi, is it possible to include the Playtime when a game is running?

**Comment by thejosejorge** [comment]
That information is available in the API so I can add it for sure!
Unfortunately due to the fact that we can't currently control the refresh rate of the widgets it may take some time for it to be updated. It could make it look like the widget is not working properly.
In summary, widgets are currently not designed to get information to the minute.

I will consider adding it as an optional feature in the next update as it should be a simple change!

**Comment by thejosejorge** [comment]
Closed on v1.1
